version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/firebase_admin_credentials.json:/app/firebase_admin_credentials.json
      - ./backend/vertex_ai_credentials.json:/app/vertex_ai_credentials.json
    command: python manage.py runserver 0.0.0.0:8000
