"""
Django settings for theramind_backend project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import json
import os
import firebase_admin
from firebase_admin import credentials
import os

SECRET_KEY = os.environ.get("SECRET_KEY")
DEBUG = os.environ.get("DEBUG") == "True"  # Ensure DEBUG is boolean for safety

PORT = os.getenv("PORT", "8080")

BASE_DIR = Path(__file__).resolve().parent.parent  # backend/
ML_MODELS_DIR = os.path.join(BASE_DIR, "ml_models")


# --- CORRECTED FIREBASE INITIALIZATION ---
# Get the Firebase credentials string from the environment variable
FIREBASE_CREDS_JSON_STRING = os.environ.get(
    "FIREBASE_APPLICATION_CREDENTIALS"
)  # Using os.environ.get directly

if FIREBASE_CREDS_JSON_STRING:
    try:
        # Crucial: Parse the JSON string into a Python dictionary
        firebase_config_dict = json.loads(FIREBASE_CREDS_JSON_STRING)

        # Pass the dictionary to credentials.Certificate()
        cred = credentials.Certificate(firebase_config_dict)

        # Initialize the Firebase app (only if not already initialized)
        if not firebase_admin._apps:  # This check is important
            firebase_admin.initialize_app(cred)
            print(
                "Firebase Admin SDK initialized successfully from environment variable in settings.py."
            )
        else:
            print("Firebase Admin SDK already initialized in settings.py.")

    except json.JSONDecodeError as e:
        print(
            f"ERROR: Could not decode Firebase credentials JSON from environment variable in settings.py: {e}"
        )
        # In production, you might want to raise an exception here to prevent app from starting
        # raise Exception(f"Failed to load Firebase credentials in settings.py: {e}")
    except Exception as e:
        print(
            f"ERROR: An unexpected error occurred during Firebase initialization in settings.py: {e}"
        )
        # raise Exception(f"Firebase initialization error in settings.py: {e}")
else:
    # This block will run if FIREBASE_APPLICATION_CREDENTIALS is not set as an environment variable
    # For local development, if you still want to use a local file, you can put that logic here.
    # Otherwise, for Heroku, this means the credentials are truly missing.
    print(
        "WARNING: FIREBASE_APPLICATION_CREDENTIALS environment variable is not set. Firebase Admin SDK will not be initialized."
    )
    # Fallback to local file for development:
    local_firebase_path = (
        BASE_DIR / "secrets" / "firebase_credentials.json"
    )  # Assumes 'secrets' folder in BASE_DIR
    if local_firebase_path.exists():
        try:
            cred = credentials.Certificate(
                str(local_firebase_path)
            )  # Path to string for credentials.Certificate
            if not firebase_admin._apps:
                firebase_admin.initialize_app(cred)
                print("Firebase Admin SDK initialized from local file in settings.py.")
        except Exception as e:
            print(f"Error initializing Firebase from local file in settings.py: {e}")


# STATIC_URL Setup: If we plan to serve static files (e.g., for admin or documentation):
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATIC_URL = "/static/"
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "0.0.0.0",  # Docker
    "theramind.site",
    "thera-mind.web.app",
    ".vercel.app",  # for subdomains
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",  # Added
    "rest_framework",  # Added
    "api",  # Added
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Added
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

from django.http import JsonResponse


def add_cors_headers(get_response):
    def middleware(request):
        response = get_response(request)
        response["Access-Control-Allow-Origin"] = (
            "http://localhost:3000"  # Allow your frontend URL
        )
        response["Access-Control-Allow-Credentials"] = (
            "true"  # Allow cookies and credentials
        )
        response["Access-Control-Allow-Methods"] = (
            "GET, POST, OPTIONS, PUT, PATCH, DELETE"
        )
        response["Access-Control-Allow-Headers"] = "Content-Type, Authorization"
        return response

    return middleware


CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https:\/\/.*\.vercel\.app$",
    r"^https:\/\/theramind\.site$",
    r"^https:\/\/thera-mind\.web\.app$",
    r"^http:\/\/localhost:3000$",
]


CORS_ALLOW_HEADERS = list(default_headers) + [
    "Content-Type",
    "Authorization",
]

CORS_ALLOW_CREDENTIALS = True


CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]


ROOT_URLCONF = "theramind_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "theramind_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.dummy"  # Dummy engine since Firestore is NoSQL
    }
}

# Add logging to track Firebase operations for debugging purposes
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


REST_FRAMEWORK = {
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
